### ISSUE TITLE
Where and How Execute Types for Adobe: Set-Up Types for Adobe command and select your target product and API version.

### ISSUE THREAD

**Issue by planewryter** [Afanyiyu/vscode-types-for-adobe#4]
Step 3 of the instructions states: _Execute "Types for Adobe: Set-Up Types for Adobe" command and select your target product and API version._

Where and how is this command executed? 

Somewhere in VSCode? In macOS Terminal? In Adobe Indesign?  

Thank you!

**Comment by ilharp** [comment]
Press <kbd>F1</kbd> (or <kbd>⌘⇧P</kbd>) and execute in VSCode. See [the GIF in README](https://github.com/ilharp/vscode-types-for-adobe).

Feel free to reopen this issue if you have any other questions.

**Comment by yozhic** [comment]
~~Amm, I installed the ExtendScript Development Pack, restarted VSCode, but the “Types for Adobe” command is not in my list. Please advise me what could be the reason.~~

It's ok, I found the reason: there was a conflict with the ExtendScript extension.
